name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Create Release on GitHub
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          generate_release_notes: true
          token: ${{ secrets.RUSSIMP_FORK_TOKEN }}

  build:
    name: Build
    needs: create-release
    runs-on: ${{ matrix.target.os }}
    strategy:
      fail-fast: false
      matrix:
        target:
          - os: ubuntu-latest
            triple: x86_64-unknown-linux-gnu
          - os: macos-latest
            triple: x86_64-apple-darwin
          - os: windows-latest
            triple: x86_64-pc-windows-msvc
        features: [ 'build-assimp', 'static-link' ]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      # LLVM comes preinstalled on Windows and macOS runners
      - name: Install LLVM
        if: runner.os == 'Linux'
        uses: KyleMayes/install-llvm-action@v1
        with:
          directory: ${{ runner.temp }}/llvm
          cached: true
          version: '14.0'

      - name: Install CMake
        uses: lukka/get-cmake@latest
        with:
          useLocalCache: true

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: ${{ matrix.target.triple }}

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target ${{ matrix.target.triple }} --features ${{ matrix.features }}

      - name: Package Assimp
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --target ${{ matrix.target.triple }} --bin package --features ${{ matrix.features }}
        env:
          RUSSIMP_PACKAGE_DIR: ./russimp-package

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
            generate_release_notes: true
            draft: true
            files: |
                ${{ env.RUSSIMP_PACKAGE_DIR }}/*
            token: ${{ secrets.RUSSIMP_FORK_TOKEN }}
        env:
          RUSSIMP_PACKAGE_DIR: ./russimp-package

  publish:
    name: Publish Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Publish release on GitHub
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          token: ${{ secrets.RUSSIMP_FORK_TOKEN }}

      - name: Create crates.io release
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --target ${{ matrix.target.triple }} --features ${{ matrix.features }} --token $CARGO_REGISTRY_TOKEN
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATESIO_TOKEN }}
