name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  create:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Create release on GitHub
        id: rel
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          generate_release_notes: true
          token: ${{ secrets.RUSSIMP_FORK_TOKEN }}
    outputs:
      upload_url: ${{ steps.rel.outputs.upload_url }}

  build:
    name: Build
    needs: create
    runs-on: ${{ matrix.target.os }}
    strategy:
      matrix:
        target:
          - os: ubuntu-latest
            triple: x86_64-unknown-linux-gnu
          - os: macos-latest
            triple: x86_64-apple-darwin
          - os: windows-latest
            triple: x86_64-pc-windows-msvc
        features: [ 'build-assimp', 'static-link' ]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      # LLVM comes preinstalled on Windows and macOS runners
      - name: Install LLVM
        if: runner.os == 'Linux'
        uses: KyleMayes/install-llvm-action@v1
        with:
          directory: ${{ runner.temp }}/llvm
          cached: true
          version: '14.0'

      - name: Install CMake
        uses: lukka/get-cmake@latest
        with:
          useLocalCache: true

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: ${{ matrix.target.triple }}

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target ${{ matrix.target.triple }} --features ${{ matrix.features }}

      - name: Package Assimp
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --target ${{ matrix.target.triple }} --bin package --features ${{ matrix.features }}
        env:
          RUSSIMP_PACKAGE_DIR: ./russimp-package

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: russimp-packages
          path: ${{ env.RUSSIMP_PACKAGE_DIR }}/*
        env:
          RUSSIMP_PACKAGE_DIR: ./russimp-package

  publish:
    name: Publish Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: russimp-packages
          path: ./russimp-package

      - name: List artifacts
        run: ls -l ./russimp-package

      - name: Publish release on GitHub
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          token: ${{ secrets.RUSSIMP_FORK_TOKEN }}
          # upload_url: ${{ needs.create.outputs.upload_url }}
          files: |
            ./russimp-package/*
          body: |
            This release was automatically created by GitHub Actions.
